kenya/county/urls.py
from django.urls import path
from .views import county_view,MainPageView,Map1PageView



app_name = 'county'
urlpatterns = [
    path('countydata/',county_view,name='county'),
    path('',MainPageView.as_view(),name='main'),
    path('map1/',Map1PageView.as_view(),name='map1'),

]

kenya/kenya/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('county.urls'))
]

kenya/county/models.py
from django.contrib.gis.db import models


class County(models.Model):
    objectid = models.IntegerField()
    area = models.FloatField()
    perimeter = models.FloatField()
    county3_field = models.FloatField()
    county3_id = models.FloatField()
    county = models.CharField(max_length=20)
    shape_leng = models.FloatField()
    shape_area = models.FloatField()
    geom = models.MultiPolygonField(srid=4326)
    county_pop= models.IntegerField(default=0)

    def __str__(self):
        return self.county


# Auto-generated `LayerMapping` dictionary for County model
county_mapping = {
    'objectid': 'OBJECTID',
    'area': 'AREA',
    'perimeter': 'PERIMETER',
    'county3_field': 'COUNTY3_',
    'county3_id': 'COUNTY3_ID',
    'county': 'COUNTY',
    'shape_leng': 'Shape_Leng',
    'shape_area': 'Shape_Area',
    'geom': 'MULTIPOLYGON',
}

kenya/county/views.py
from django.shortcuts import render
import json
from django.http import JsonResponse , HttpResponse
from django.core.serializers import serialize
from .models import County
from django.views.generic import  TemplateView
from django.core.cache import cache
# Create your views here.
"""def county_view(request):
    county_geojson = serialize('geojson',County.objects.all())
    return JsonResponse(json.loads(county_geojson))
"""


def county_view(request):
    counties = serialize('geojson', County.objects.all())
    #return HttpResponse(counties, content_type='application/json')
    return JsonResponse(json.loads(counties))


class MainPageView(TemplateView):
    template_name = 'county/main.html'

class Map1PageView(TemplateView):
    template_name = 'county/map1.html'

kenya/county/templates/county/main.html
<!DOCTYPE html>
<html>
{% load leaflet_tags %}
{% load static %}
    <head>
        <style media="screen">
     #gis { width:100%; height:200% }
   </style>
        {% leaflet_js %}
        {% leaflet_css %}
        <script src="{% static 'county/js/leaflet.ajax.js' %}"></script>
        <script src="{% static 'county/js/leaflet.spin.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    </head>
    <body>
    {% leaflet_map "main" callback="main_map_init" %}

            <script type="text/javascript">
                function main_map_init (map, options) {
                    var dataurl = '{% url "county:county" %}';
            // Download GeoJSON via Ajax
            $.getJSON(dataurl, function (data) {
                // Add GeoJSON layer
                L.geoJson(data,{
                    onEachFeature: function (feature, layer) {
                        layer.bindPopup("<b><u>Details</u></b>"+
                                "<p><b>Name:</b> "+feature.properties.county+"</p>"+
                                "<p><b>Population:</b> "+feature.properties.county_pop+"</p>");
                        }
                    }).addTo(map);
            });
                }
            </script>


    </body>
</html>

kenya/county/templates/county/map1.html
<html>
<head>
    {% load leaflet_tags %}
  <meta charset="utf-8" />
  <title>Switching basemaps</title>
  <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />

  <!-- Load Leaflet from CDN -->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>
  <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
  integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
  crossorigin=""></script>


  <!-- Load Esri Leaflet from CDN -->
  <script src="https://unpkg.com/esri-leaflet@2.3.0/dist/esri-leaflet.js"
  integrity="sha512-1tScwpjXwwnm6tTva0l0/ZgM3rYNbdyMj5q6RSQMbNX6EUMhYDE3pMRGZaT41zHEvLoWEK7qFEJmZDOoDMU7/Q=="
  crossorigin=""></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

  <style>
    body { margin:0; padding:0; }
    #map { position: absolute; top:0; bottom:0; right:0; left:0; }
  </style>
</head>
<body>

<style>
  #basemaps-wrapper {
    position: absolute;
    top: 10px;
    right: 10px;
    z-index: 400;
    background: white;
    padding: 10px;
  }
  #basemaps {
    margin-bottom: 5px;
  }
</style>

<div id="map"></div>

<div id="basemaps-wrapper" class="leaflet-bar">
  <select id="basemaps">
    <option value="Topographic">Topographic</option>
    <option value="Streets">Streets</option>
    <option value="NationalGeographic">National Geographic</option>
    <option value="Oceans">Oceans</option>
    <option value="Gray">Gray</option>
    <option value="DarkGray">Dark Gray</option>
    <option value="Imagery">Imagery</option>
    <option value="ImageryClarity">Imagery (Clarity)</option>
    <option value="ImageryFirefly">Imagery (Firefly)</option>
    <option value="ShadedRelief">Shaded Relief</option>
    <option value="Physical">Physical</option>
  </select>
</div>

<script>

   var map = L.map('map').setView([-.023,36.87], 6);
   var layer = L.esri.basemapLayer('DarkGray').addTo(map);
   var dataurl = '{% url "county:county" %}';

   function onEachFeature(feature, layer) {
                layer.bindPopup("<b><u>Details</u></b>"+
                                "<p><b>Name:</b> "+feature.properties.county+"</p>"+
                                "<p><b>Population:</b> "+feature.properties.county_pop+"</p>");
                }
    function getColor(d) {
		return d > 2380000 ? '#B10026' :
				d > 1650000  ? '#E31A1C' :
				d > 1340000  ? '#FC4E2A' :
				d > 1130000  ? '#FD8D3C' :
				d > 865000   ? '#FEB24C' :
				d > 630000   ? '#FED976' :
				d > 378000   ? '#FFEDA0' :
							'#FFFCCC';
	}
	function style(feature) {
		return {
			weight: 2,
			opacity: 1,
			color: 'white',
			dashArray: '3',
			fillOpacity: 0.7,
			fillColor: getColor(feature.properties.county_pop)
		};
	}


    // Download GeoJSON via Ajax
    $.getJSON(dataurl, function (data) {
        // Add GeoJSON layer

        L.geoJson(data,{
            style:style,
            onEachFeature:onEachFeature
            }).addTo(map);
    });
  var layerLabels;

  function setBasemap (basemap) {
    if (layer) {
      map.removeLayer(layer);
    }

    layer = L.esri.basemapLayer(basemap);

    map.addLayer(layer);

    if (layerLabels) {
      map.removeLayer(layerLabels);
    }

    if (
      basemap === 'ShadedRelief' ||
      basemap === 'Oceans' ||
      basemap === 'Gray' ||
      basemap === 'DarkGray' ||
      basemap === 'Terrain'
    ) {
      layerLabels = L.esri.basemapLayer(basemap + 'Labels');
      map.addLayer(layerLabels);
    } else if (basemap.includes('Imagery')) {
      layerLabels = L.esri.basemapLayer('ImageryLabels');
      map.addLayer(layerLabels);
    }
  }

  document
    .querySelector('#basemaps')
    .addEventListener('change', function (e) {
      var basemap = e.target.value;
      setBasemap(basemap);
    });
</script>

</body>
</html>